name: jcombu
description: Japanese charset convertor from SJIS/EUC/JIS(ISO-2022-JP) to Dart String.
version: 0.1.0
homepage: https://github.com/moonsightz/jcombu/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
