name: jcombu
description: Japanese charset converter from SJIS/EUC-JP/JIS(ISO-2022-JP) to Dart String (pure dart implementation).
version: 1.1.1
homepage: https://github.com/moonsightz/jcombu/

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
